### ISSUE TITLE
如何保护自己的时间

### ISSUE THREAD

**Issue by Alan110** [Alan110/1024.dog#1]
ss

**Comment by kilyliu** [comment]
目前的情况是为了保证things不被忘记，采取了接受后立马开始做的情况

**Comment by Alan110** [comment]
我也有很多事情，很多人找，很烦，没有多少整段的时间去写代码，或者整理自己的思想。

**我知道的是人不适合频繁的切换思考模式，切换是有成本的，所有要尽量去保证自己有整段的时间。深入工作和思考**

我现在做法是

* 早上起得比较早，然后去得比较晚，利用这2个小时的时间，去深度自考那些最难的问题，和整理，以及规划。
* 然后如果在公司很多人找让我很烦，我就会拿电脑去别的安静的地方躲一阵，比如茶水间啊，会议室啊什么的。

**Comment by kilyliu** [comment]
微信群里会各种@我询问相关“很紧急”的问题，立即做出反应是我的本职工作，所以肯定没办法说不回应，但是可考虑从源头上减少此类问询的次数，如：
* 提供常见的咨询问题及答案列表
* 避免由于情绪问题造成不必要的麻烦，可先准备一些官方的回答模板
* 整理出哪一类问题才应该咨询我的wiki

**Comment by kilyliu** [comment]
我是不是应该在为自己的工作深入思考提供一些私人时间，而不是寄托在上班时间？

**Comment by Alan110** [comment]
* **减少别人找你的理由，或者说让别在找你之前就知道了他想知道的东西**
* **让别人按照你的规律，节奏来办事**

第一点
* 可以让一些简单的问题自动化，比如wiki，比如问答机器人
* 不必亲自来回答，让别人回答，比如实习生，比如具体的负责人，我们只负责转发

**Comment by Alan110** [comment]
### 事情优先级
![image](https://user-images.githubusercontent.com/7564425/32055915-bb5def5e-ba95-11e7-998b-d0d9178642f9.png)

管理时间的秘诀就是：有条理的强制自己关注那些重要的事情，抑制住对紧急的事情的冲动。

作者：李诺
链接：https://www.zhihu.com/question/19705539/answer/25650634
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

、学会拒绝：大部分人在遵守一种隐藏的社会道德——当有人请你帮忙的时候，你总是要说——YES。这可能听起来很高尚，但是别忘了有一个快要死去的公主等着你去救命呢，就因为别人很礼貌的请你帮忙，你就可以慢下来。你可能需要牺牲一下社交上的舒适感去救你的公主（最为奖励，人们普遍会对那些能够拒绝的人有一种本能的尊重）。2、关掉电脑：如果你长达7年不玩电脑，你就会比那些每周平均花费34个小时在电脑娱乐上的人来说多了12376个小时。我当然也会用电脑娱乐，但是只是在休息的时候看上半个小时，但是只有半个小时。你可以使用12000个小时做很多事情，追赶上那些疯狂的人。3、关掉通知：现代科技已经进化到可以利用我们对紧急事情的嗜好了：邮件，微博，QQ，知乎等等争先恐后的抢走你的注意力。幸运的是，有一个简单的方法可以解决它：关掉所有的通知。当你有时间思想不集中的时候再去处理那些事情，比如饭后休息的时候，然后把那些事情集中解决，这样可以节省时间。4、为你的事情的优先级做计划：人类是种很有趣的生物，如果你要去见朋友，你得安排一个确定的时间去看他，但是如果你有一些事情恰恰是和你自己有关系，比如写一本书，或者去健身房，那么你却不会安排好日程。你就是想避开它。把你优先级最高的事情视作你要赶上的航班：预先约定好时间，然后对所有阻挡你的航班的事情说不。5、最重要的事情先做：你现在能做的最重要的事情（不是最紧急的）是什么？今天做一部分。记住分散你注意力的冲锋队是无穷无尽的，别用“我就先做这些事情，一会做那些最重要的事情”这样的想法骗自己。你不是靠这些借口活着的。6、更多的时间，更少的事情：你可能同时正在做成百上千件事，有一个小诀窍是一天最多做1到3件事，而且持续为之努力。你的大脑不喜欢这个限制，其他人也不会喜欢这个限制。但是无论如何这样做。把自己的注意力放在一件事情上要比同时做多件事要有效率的多。为熟练自己的工作多匀一点时间出来。7、忽略：这是很粗鲁、不道德但是却相当必要的。总是有些人你是没空去搭理他们的。你必须允许自己忘记一些请求。你可以晚一点去做打扫、付帐单、回复邮件这些事情。这个世界是不会崩溃的。而这样做的报酬是——你完成了那些真正重要的事情。


### 目标制定
* 目标需要是可度量的
* 目标应该有截止日期，没有截止日期，也就没有开始
* 目标分成A,B,C三个优先级，和短期、中期和长期
