### ISSUE TITLE
阅读能带给我们什么？

### ISSUE THREAD

**Issue by kilyliu** [Alan110/1024.dog#4]

**Comment by kilyliu** [comment]
将健身事业进行到底

**Comment by kilyliu** [comment]
- [ ] 《腾讯传》-kily-nosummary
- [ ] 《》

**Comment by kilyliu** [comment]
人们常说阅读能提升一个人的气质，那么我们都应该阅读什么类型的书籍呢？看小说算是一种阅读吗？

**Comment by Alan110** [comment]
看小说也一样是阅读，当然得看这个小说的内涵有多少，你又能从中汲取多少。大部分小说都是以娱乐为主，并没有什么文学素养，或者标新立异的思想。现在的网文，大部分归为此类。但是你说看金庸的小说，有没有什么好处？红楼梦不也是小说？

所以阅读是否一定有益，这不好说，好的读书人遇上烂书没用，不好的读书人遇上好书也没用。

**选择一本适合自己的好书，用良好的方式去阅读，反思沉淀才能从书中汲取精华**。

**对于自己读的书一定要谨慎**，它会潜移默化的影响你思想，如果你没有坚定有力的正知正见，而又看了很多邪知邪见，这是很危险的

**Comment by kilyliu** [comment]
# 阅读是要分类型的
* 娱乐消遣：网络小说，头条小报，阅读这类内容是完全不用脑的，阅读的时候会获得愉快的体验，但是时间长了会使得我们精神恍惚，没有营养的东西看得少能成为放松的娱乐，但是时间长了会使得我们的大脑懒惰，变得懒于思考。
* 获取咨询：杂志，畅销书等，能帮助我们获取更多的外界信息，能增加一定知识，但是并不能促进大脑的理解能力。
* 增进理解：需要思考的书籍需要我们有一定的方法论，需要待着思考的态度去进行阅读，长期保持阅读能够促进大脑理解力。
# 阅读需要找到一本书的“骨架”
能过使用一句话或简单的段落来叙述整本书的内容，通过找到书的关键词来组合成一段话即可。

**Comment by kilyliu** [comment]
我想，阅读能带来的东西在阅读前是永远也无法想象到的，所以我决定关掉这个issue去真正的阅读中寻找阅读的意义
